/**
 * Honest capability matrix (single source of truth). Rendered in the UI (#/capabilities) and in
 * docs/CAPABILITIES.md (generated by `npm run docs:capabilities`; a test fails if they drift).
 *
 * Columns:
 *  - simulated:   the real-world part is replaced by a simulation or mock here
 *  - implemented: working code exists in this repository
 *  - evaluated:   checked by automated tests/scripts in this repository ONLY. No row has been
 *                 evaluated with real users, real radios, or in the field.
 *  - future:      not built, or only the prototype part is built
 */
export interface Capability {
  area: string;
  capability: string;
  simulated: boolean;
  implemented: boolean;
  evaluated: 'automated tests' | 'measured by script' | 'none';
  future: string;
  evidence: string;
}

export const CAPABILITIES: Capability[] = [
  {
    area: 'A. Patient and assisted app',
    capability:
      'Screens A-H, 3 languages, assisted mode, 320px/RTL/200% text, request correction, Finish/lock',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Usability testing with patients and health workers; more languages',
    evidence: 'Playwright journeys at 320px and 1280px; axe 0 violations on recorded screens',
  },
  {
    area: 'A. Patient and assisted app',
    capability: 'Voice input (speech-to-text) with typing fallback',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future:
      'Real-browser accuracy for en/sw/ar is UNKNOWN; browser may send audio to a third party',
    evidence: 'Unit tests with deterministic mock; e2e with scripted fake Web Speech API',
  },
  {
    area: 'B. Village node service',
    capability:
      'Durable acceptance (fsynced write-ahead journal), replay after restart, torn-write recovery',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Target hardware; at-rest encryption; backup; separate asset cache',
    evidence: 'Restart, power-cut and real-process SIGKILL tests',
  },
  {
    area: 'B. Village node service',
    capability:
      'Node health indicators (availability, storage, queue age, radio adapter status, last sync)',
    simulated: true,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Real radio adapter status; battery and temperature from hardware',
    evidence: 'GET /api/node/health; unit test',
  },
  {
    area: 'C. Transport',
    capability:
      'Fixed route, stable ids, per-hop custody acks, bounded retry with backoff, TTL, dedupe',
    simulated: true,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Real radio links, framing, FEC, encryption; field range and airtime measurement',
    evidence: 'Deterministic simulator tests (loss, lost ack, duplicate, reorder, outage, expiry)',
  },
  {
    area: 'D. Gateway',
    capability: 'Explicit module with its own inbox/outbox; independent radio vs upstream outages',
    simulated: true,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Separate gateway process and disk; real upstream connectivity',
    evidence: 'Gateway tests: upstream outage, return-side radio outage, duplicate on radio side',
  },
  {
    area: 'E. Clinic app',
    capability:
      'Inbox, claim, original + optional draft summary, human-approved replies, delivery history',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Review with real clinicians; clinical safety review of templates and wording',
    evidence: 'Service and Playwright tests; reply unsent until clinician approval',
  },
  {
    area: 'E. Clinic app',
    capability: 'Clarification question (approved, linked) and linked follow-up in the same case',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Structured question templates',
    evidence: 'Service tests; Playwright demo',
  },
  {
    area: 'E. Clinic app',
    capability:
      'Team coverage statement, overdue vs review window, handover, closure with explicit outcome',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Rota integration; real service-hours calendar; escalation rules',
    evidence:
      'Service tests; staffing is a stated value, never inferred; closure asserts no health outcome',
  },
  {
    area: 'F. AI and language assistance',
    capability: 'Draft summary of the request',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'AI model assistance, with its own availability, model version and data policy',
    evidence:
      'Deterministic rules, NO AI model; always labelled a draft to verify against the original',
  },
  {
    area: 'F. AI and language assistance',
    capability: 'Translation',
    simulated: true,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Real translation service with native-speaker review',
    evidence: 'Mock phrase dictionary only; always flagged as needing review; original preserved',
  },
  {
    area: 'G. Integration',
    capability: 'Canonical model, per-destination adapters (DHIS2, FHIR), ack/retry/reconciliation',
    simulated: false,
    implemented: false,
    evaluated: 'none',
    future: 'Entire module. No FHIR or DHIS2 interoperability is claimed',
    evidence: 'Not built',
  },
  {
    area: 'H. Administration',
    capability:
      'Consent wording version, service hours, review window, retention setting, attributed config changes',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future:
      'Facilities, nodes, staff access management, language packs, incidents. The retention number is recorded but NOT enforced',
    evidence: 'Admin config endpoints with audit events',
  },
  {
    area: 'Cross-cutting',
    capability:
      'Role-based permissions enforced in the service (patient secret, CHW, reviewer, coordinator, operator, admin)',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Real identity and credential management; integration accounts; security review',
    evidence:
      'Unauthorized-access tests at service and HTTP level. Demo tokens are NOT real authentication',
  },
  {
    area: 'Cross-cutting',
    capability: 'Consent records and audit events (identifiers only, no content)',
    simulated: false,
    implemented: true,
    evaluated: 'automated tests',
    future: 'Legal review of consent wording and retention; tamper-evident audit storage',
    evidence: 'Tests assert audit data holds no names or message text',
  },
  {
    area: 'Cross-cutting',
    capability: 'Patient-unavailable workflow (pending-reply indicator, no-detail notifications)',
    simulated: false,
    implemented: false,
    evaluated: 'none',
    future: 'Not built',
    evidence: 'Not built',
  },
  {
    area: 'Cross-cutting',
    capability: 'At-rest encryption of the journal and drafts',
    simulated: false,
    implemented: false,
    evaluated: 'none',
    future: 'Required before any real data',
    evidence: 'Not built; synthetic data only',
  },
];

export interface LanguageCapability {
  language: string;
  code: 'en' | 'sw' | 'ar';
  uiText: string;
  speech: string;
  translation: string;
  review: string;
}

export const LANGUAGE_CAPABILITIES: LanguageCapability[] = [
  {
    language: 'English',
    code: 'en',
    uiText: 'Implemented (authored here; no clinical-wording review)',
    speech: 'Adapter sends en-US to the browser Web Speech API; accuracy UNKNOWN',
    translation: 'Not needed for the clinic; clinic replies are written in English',
    review: 'Not reviewed by a clinical or language reviewer',
  },
  {
    language: 'Swahili',
    code: 'sw',
    uiText: 'Implemented, UNREVIEWED demo strings',
    speech: 'Adapter sends sw-KE; browser support and accuracy UNKNOWN',
    translation: 'Mock phrase dictionary (tiny); always flagged "needs review"; original kept',
    review: 'UNREVIEWED: needs a native-speaker medical reviewer',
  },
  {
    language: 'Arabic (right-to-left)',
    code: 'ar',
    uiText: 'Implemented, UNREVIEWED demo strings, RTL layout',
    speech: 'Adapter sends ar-SA; browser support and accuracy UNKNOWN',
    translation: 'Mock phrase dictionary (tiny); always flagged "needs review"; original kept',
    review: 'UNREVIEWED: needs a native-speaker medical reviewer',
  },
];

const yn = (b: boolean) => (b ? 'Yes' : '-');

/** Markdown for docs/CAPABILITIES.md. */
export function capabilitiesMarkdown(): string {
  const lines: string[] = [
    '# Capability matrix',
    '',
    '> **SIMULATION. SYNTHETIC DATA ONLY. Not production-ready.** Generated from `src/shared/capabilities.ts` by `npm run docs:capabilities`; shown in the app at `#/capabilities`.',
    '',
    '- **Simulated**: the real-world part is replaced by a simulation or mock.',
    '- **Implemented**: working code exists in this repository.',
    '- **Evaluated**: checked by automated tests or scripts here **only**. Nothing has been evaluated with real users, real radios, or in the field.',
    '- **Future**: what is not built or still missing.',
    '',
    '| Area | Capability | Simulated | Implemented | Evaluated | Future / missing | Evidence and caveats |',
    '| --- | --- | :-: | :-: | --- | --- | --- |',
  ];
  for (const c of CAPABILITIES)
    lines.push(
      `| ${c.area} | ${c.capability} | ${yn(c.simulated)} | ${yn(c.implemented)} | ${c.evaluated} | ${c.future} | ${c.evidence} |`,
    );
  lines.push(
    '',
    '## Language capability matrix',
    '',
    '| Language | UI text | Speech input | Translation | Review status |',
    '| --- | --- | --- | --- | --- |',
  );
  for (const l of LANGUAGE_CAPABILITIES)
    lines.push(`| ${l.language} | ${l.uiText} | ${l.speech} | ${l.translation} | ${l.review} |`);
  lines.push(
    '',
    '## Missing field-pilot prerequisites (not done)',
    '',
    '- Country radio authorization and spectrum plan (amateur radio is not a deployment basis).',
    '- Real radio hardware, power, enclosure, range and airtime measurements.',
    '- Usability and comprehension testing with patients, community health workers and clinicians.',
    '- Native-speaker medical review of every language pack and translation.',
    '- Clinical safety review of templates, draft rules and escalation wording.',
    '- Security and privacy review, at-rest encryption, real identity management.',
    '- Consent wording and data-retention legal review; enforced retention.',
    '- Integration design with the destination health information systems.',
    '- Operations: staffing, incident process, support, upgrades and backups.',
    '',
  );
  return lines.join('\n');
}
