/** WCAG 2.x contrast ratios for the palette in src/web/styles.css. Run: npx tsx scripts/contrast.ts */
import fs from 'node:fs';

const css = fs.readFileSync('src/web/styles.css', 'utf8');
const v = (name: string): string => {
  const m = new RegExp(`--${name}:\\s*(#[0-9a-fA-F]{6})`).exec(css);
  if (!m) throw new Error(`missing --${name}`);
  return m[1]!;
};
const lum = (hex: string) => {
  const [r, g, b] = [1, 3, 5].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  }) as [number, number, number];
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const ratio = (a: string, b: string) => {
  const [hi, lo] = [lum(a), lum(b)].sort((x, y) => y - x) as [number, number];
  return (hi + 0.05) / (lo + 0.05);
};

const pairs: Array<[string, string, string, number]> = [
  ['text on page background', 'text', 'bg', 4.5],
  ['text on card surface', 'text', 'surface', 4.5],
  ['muted text on page background', 'muted', 'bg', 4.5],
  ['muted text on card surface', 'muted', 'surface', 4.5],
  ['muted text on accent-soft notice', 'muted', 'accent-soft', 4.5],
  ['text on accent-soft notice', 'text', 'accent-soft', 4.5],
  ['accent link/secondary button text on bg', 'accent', 'bg', 4.5],
  ['accent secondary button text on surface', 'accent', 'surface', 4.5],
  ['primary button text on accent', 'accent-contrast', 'accent', 4.5],
  ['alert text on alert background', 'alert-text', 'alert-bg', 4.5],
  ['simulation banner text on banner', 'banner-text', 'banner-bg', 4.5],
  ['control border on page background (non-text 3:1)', 'border', 'bg', 3],
  ['control border on card surface (non-text 3:1)', 'border', 'surface', 3],
  ['focus ring on page background (non-text 3:1)', 'focus', 'bg', 3],
  ['focus ring on card surface (non-text 3:1)', 'focus', 'surface', 3],
  ['focus ring on accent-soft notice (non-text 3:1)', 'focus', 'accent-soft', 3],
];
const lines = ['| Pair | Ratio | Required | Result |', '| --- | ---: | ---: | --- |'];
let fail = 0;
for (const [label, fg, bg, need] of pairs) {
  const r = ratio(v(fg), v(bg));
  const ok = r >= need;
  if (!ok) fail++;
  lines.push(`| ${label} | ${r.toFixed(2)}:1 | ${need}:1 | ${ok ? 'pass' : 'FAIL'} |`);
}
const out = lines.join('\n');
fs.mkdirSync('docs/measurements', { recursive: true });
fs.writeFileSync(
  'docs/measurements/contrast.md',
  `# Contrast ratios (computed from src/web/styles.css)\n\nGenerated by \`npx tsx scripts/contrast.ts\`. The focus ring is drawn 2px OUTSIDE the control (outline-offset), so it is measured against the surrounding backgrounds. FACT: computed values. Automated axe color-contrast checks are reported separately in VERIFICATION.md.\n\n${out}\n`,
);
console.log(out);
process.exitCode = fail ? 1 : 0;
