/**
 * Measures encoded request sizes of the PROTOTYPE codec (not a real radio protocol).
 * Run: npm run evidence:bytes   (writes docs/measurements/request-bytes.md)
 *
 * Conditions (also written into the output):
 *  - inputs: synthetic fixtures below, UTF-8, English/Swahili/Arabic demo text
 *  - messageId: 16-byte UUID; no encryption, no FEC, no compression unless stated
 *  - "JSON" = JSON.stringify({messageId, input}) as sent over local HTTP (UTF-8 bytes)
 *  - "codec" = src/shared/codec.ts output; "codec+deflate" = zlib.deflateRawSync(level 9) of codec
 *  - frame counts use an ASSUMED framing (8 bytes overhead per frame: 6-byte header + 2-byte CRC);
 *    airtime lines are plain arithmetic at ASSUMED link rates, NOT measured RF performance.
 */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { encodeRequest, decodeRequest } from '../src/shared/codec';
import { NOOR_INPUT, NOOR_INPUT_AR, NOOR_INPUT_SW } from '../src/shared/fixtures';
import type { RequestInput } from '../src/shared/types';

const ID = '11111111-2222-4333-8444-555555555555';
const long = (n: number) => 'I need a follow-up appointment next week. '.repeat(40).slice(0, n);

const cases: Array<{ name: string; input: RequestInput }> = [
  { name: 'Noor, English (fixture)', input: NOOR_INPUT },
  { name: 'Noor, Swahili (UNREVIEWED demo)', input: NOOR_INPUT_SW },
  { name: 'Noor, Arabic (UNREVIEWED demo)', input: NOOR_INPUT_AR },
  {
    name: 'Minimal: type + 12-char note, no name/village',
    input: { ...NOOR_INPUT, patientName: '', village: '', details: 'Need a visit', contact: '' },
  },
  {
    name: 'Assisted entry, English, with contact',
    input: {
      ...NOOR_INPUT,
      entryMode: 'assisted',
      assistedBy: 'Grace (synthetic)',
      contact: 'via CHW Grace',
    },
  },
  { name: 'Long note: 300 chars English', input: { ...NOOR_INPUT, details: long(300) } },
  { name: 'Max note: 1000 chars English', input: { ...NOOR_INPUT, details: long(1000) } },
];

const FRAME_OVERHEAD = 8;
const FRAME_PAYLOADS = [48, 128, 200];
const RATES = [1200, 9600];

const rows: string[] = [];
for (const c of cases) {
  const json = Buffer.byteLength(JSON.stringify({ messageId: ID, input: c.input }));
  const bin = encodeRequest(c.input, ID);
  const rt = decodeRequest(bin);
  if (JSON.stringify(rt.input) !== JSON.stringify(c.input))
    throw new Error(`round-trip failed: ${c.name}`);
  const def = zlib.deflateRawSync(Buffer.from(bin), { level: 9 }).length;
  const frames = FRAME_PAYLOADS.map((p) => Math.ceil(bin.length / p));
  rows.push(
    `| ${c.name} | ${Buffer.byteLength(c.input.details)} | ${json} | ${bin.length} | ${def} | ${frames.join(' / ')} |`,
  );
}

const air = cases
  .slice(0, 3)
  .map((c) => {
    const n = encodeRequest(c.input, ID).length;
    return `| ${c.name} | ${n} | ${RATES.map((r) => (((n + FRAME_OVERHEAD * Math.ceil(n / 128)) * 8) / r).toFixed(2)).join(' s / ')} s |`;
  })
  .join('\n');

const out = `# Encoded request size measurements

Generated by \`npm run evidence:bytes\` (scripts/measure-bytes.ts). **FACT** for the byte counts below
(measured by running the script on the stated inputs). The framing and airtime lines are **INFERENCE**
(arithmetic on assumptions), not RF measurements.

## Conditions
- Prototype codec (\`src/shared/codec.ts\`), not a standardized radio protocol. No encryption, FEC or radio framing in the codec itself.
- 16-byte UUID message id, UTF-8 text, synthetic fixtures only. Every case round-trips (decode equals input) before being counted.
- JSON = \`JSON.stringify({messageId, input})\` (what the browser POSTs to the local node).
- codec+deflate = raw DEFLATE level 9 of the codec bytes (Node zlib).
- The 300/1000-character cases repeat one sentence, so their deflate sizes are unrealistically small and must not be generalized to real notes.
- Frames: ASSUMED payload sizes ${FRAME_PAYLOADS.join(' / ')} bytes; ASSUMED ${FRAME_OVERHEAD} bytes overhead per frame (6-byte header + 2-byte CRC), not in the codec.

| Case | note bytes (UTF-8) | JSON bytes | codec bytes | codec+deflate bytes | frames at ${FRAME_PAYLOADS.join('/')} B payload |
| --- | ---: | ---: | ---: | ---: | --- |
${rows.join('\n')}

## Arithmetic airtime at ASSUMED link rates (128 B frames, ${FRAME_OVERHEAD} B overhead each; no retries, no turnaround, no protocol overhead)
| Case | codec bytes | time at ${RATES.join(' bps / ')} bps |
| --- | ---: | --- |
${air}

These are not measured radio results. Real airtime depends on modulation, FEC, retries, duty-cycle limits and
authorization in the country of deployment, all UNKNOWN here.
`;
fs.mkdirSync('docs/measurements', { recursive: true });
fs.writeFileSync(path.join('docs/measurements', 'request-bytes.md'), out);
console.log(out);
